config {
  type: "table",
  schema: "promotions_analysis",
  description: "Revenue per product, city, date"
}
select
  date,
  city,
  ${functions.regionGroup("city")} as region,
  a.uniq_id,
  c.Product_Name_New,
  sum(a.price_total) revenue
from
  ${ref("virtualshop_orders_sku")} a
  JOIN ${ref("promo")} c ON a.uniq_id=c.Product_ID
WHERE
  date >= (${functions.last30day(
      `${ref("virtualshop_orders_sku")}`,
      "date"
    )}
  )
group by 1,2,3,4,5
